config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, except: [:index, :destroy]
  resources :categories, only: [:show, :index]

  post "/posts" => "posts#create"
  get "/register", to: "users#new"
  get "/login", to: "sessions#new"
  get "users/:id/edit" => "users#edit"
  get "posts/:id/edit" => "posts#edit", as: :edit_post
  get "posts/:id" => "posts#show", as: :post

  patch "posts/:id" => "posts#update"
  delete "posts/:id" => "posts#destroy"

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_and_belongs_to_many :users
  has_many :posts

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :category
  belongs_to :user

  validates :description, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_and_belongs_to_many :categories
  has_many :post

  has_secure_password
    validates :email, presence: true, uniqueness: {case_sensitive: false}

    validates :user_name, presence: true, uniqueness: {case_sensitive: false}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

    helper_method :current_user

    def current_user
      if session[:user_id]
      @current_user ||= User.find(
        session[:user_id])
      end
    end

    def authorize
      if current_user.nil?
          redirect_to login_path, alerts: 'Not authorized - you must be logged in!'
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def index
        @categories = Category.all
    end

    def show
        @post = Post.new
        @category = Category.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :only_my_post, only: [:edit, :update, :destroy]

    def create
      @post = Post.new(post_params)
      @post.user_id = @post.user_id.to_i
        respond_to do |format|
          if @post.save
            format.html { redirect_to @post.category, notice: "Post was successfully created." }
            format.json { render :show, status: :created, location: @post }
          else
            format.html { redirect_to @post.category, notice: @post.errors.full_messages.to_sentence }
            format.json {render json: @post.errors, status: :unprocessable_entity }
          end
        end
    end

    def index
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
          render "post"
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])

      if @post.update_attributes(post_params)
          redirect_to post_path(@post)
      else
          render :edit
      end
    end

    def destroy
        @post = Post.find(params[:id])
        category = @post.category
        @post.destroy
        redirect_to category_path(category)
    end

    private

    def post_params
        params.require(:post).permit(:description, :user_id, :category_id )
    end
    def set_post
        @post = Post.find(params[:id])
    end

    def only_my_post
        @post = Post.find(params[:id])
        redirect_to @post.category, notice: "Must be original publisher" if (current_user.id != @post.user.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
      user = User.find_by(user_name: params[:user_name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = 'Invalid login credentials - Try again!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    puts user_params
    user = User.new(user_params)
    if user.save
        flash[:success] = 'You have successfully created User Login!'
        session[:user_id]
        redirect_to root_path
    else
        flash[:error] = 'Creating User has failed!'
        redirect_to new_user_path, notice: 'Please, try creating again.'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      if current_user.id == @user.id
        redirect_to categories_path
      end
    else
      render :edit
    end
  end

  def edit
      @user = User.find(params[:id])
  end

  def show
  end

  private

  def user_params
      params.require(:user).permit(:first_name, :last_name, :user_name, :city, :state, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/index.html.erb
<link href='https://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>

<h2>Select a Category</h2>

  <% @categories.each do |category| %>
  <div class="container" "gallery-cell" id="category-list">
  <div class="category btn btn-default col-xs-1 col-sm-2">
  <div class='row'>
  <%= link_to category.topic, category_path(category) %>
  </div>
  </div>
  </div>
<% end %>

app/views/categories/show.html.erb
<link href='https://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Dosis:400,800' rel='stylesheet' type='text/css'>

<div class="category-container">
<div class="body">

<h1> <%= @category.topic %> </h1>

    <div class="post-scroll">
        <% @category.posts.each do |post| %>
        <div><%= post.description %></div>

        <div class='post-user'>
        <%= post.user.user_name %>
    </div>

    <div class='edit-tab' >
        <%= link_to 'Edit Post', edit_post_path([post.id]), method: :get, class: "btn btn-default btn-xs" %>
    </div>
    <%end%>
    </div>
</select>

    <div class="description">
        <%= form_for @post do |f| %>
        <% flash.each do |key, msg| %>
    <div><%= msg %></div>
    <% end %>

        <%= f.hidden_field :category_id, :value => params[:id] %>

        <%= f.hidden_field :user_id, :value => session[:user_id] %>

        <%= f.text_area :description %>
    <h3>Share Something GOOD!</h3>
    <div class='post-button'>
        <%= f.submit "Post", class: "btn btn-default btn-sm" %>
    </div>
    </div>
    <% end %>
</div>
</div>

app/views/layouts/_navbar.html.erb
<HEADER>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-left">
       <% if current_user %>
          <li><a><strong><%= current_user.user_name %></strong></a></li>
          <li><%= link_to 'Logout', session_path('dummy'), method: :delete %></li>
          <li><%= link_to 'Edit Profile', edit_user_path(session[:user_id]), method: :get %></li>
          <li><%= link_to 'Categories', categories_path %></li>
        <% else %>
          <%= link_to '', login_path %>
          <%= link_to '', new_user_path %>

        <% end %>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'New User', new_user_path %></li>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Login', login_path %></li>
      </ul>
    </div>
  </div>
</nav>


</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project2ShareSomethingGood</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<body class="<%= "category-#{@category.topic}" if @category %>">
    <%= render 'layouts/navbar' %>

<%= yield %>
</body>
</html>

app/views/posts/edit.html.erb
<link href='https://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>

<h1>Edit this post!</h1>

<div class="edit-post">

<%= form_for @post, url: "/posts/#{params[:id]}", method: "patch" do |f| %>
      <%= f.label :description %>
      <%= f.text_field :description %>

</div>

    <%= f.submit "Submit these changes!", class: "btn btn-default btn-xs" %>

<% end %>

<%= link_to "Post page", category_path(@post.category), class: "btn btn-default btn-xs" %>
<%= link_to "Delete", post_path, method: :delete, data: { confirm: "Are you sure you want to delete this Post?"}, class: "btn btn-default btn-xs" %>

</div>

app/views/posts/index.html.erb
<link href='https://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>

<h1>Today's Posts</h1>

<ul>
    <% @posts.each do |post| %>
        <li>
            <strong><%= post.user_id %></strong> - <%= post.decription %>
            <%= link_to "More info", post_path(post) %>
        </li>
    <% end %>
</ul>

app/views/posts/new.html.erb
<h1>Write Post</h1>


    <%= form_for @post do |f| %>
    <% flash.each do |key, msg| %>
<div><%= msg %></div>
    <% end %>

    <%= f.hidden_field :category_id, :value => params[:category_id] %>
    <%= f.hidden_field :user_id, :value => session[:user_id] %>
    <%= f.text_area :description %>

<div class='post-button'>
    <%= f.submit "Post" %>
</div>

<% end %>

app/views/posts/post.html.erb
<h1>Write Post</h1>


<%= form_for @post do |f| %>
    <% flash.each do |key, msg| %>
<div><%= msg %></div>
<% end %>

    <%= f.hidden_field :category_id, :value => params[:category_id] %>
    <%= f.hidden_field :user_id, :value => session[:user_id] %>
    <%= f.text_area :description %>

<div class='post-button'>
    <%= f.submit "Post" %>
</div>

<% end %>

app/views/posts/show.html.erb
<link href='https://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>

<div class=post-update>
<h1><%= @post.user.user_name %></h1>

<p><%= @post.description %></p>


    <%= link_to "Edit", edit_post_path(@post), class: "btn btn-default btn-xs" %>

    <%= link_to "Back to Post", category_path(@post.category_id), class: "btn btn-default btn-xs" %>
</div>

app/views/users/edit.html.erb
<link href='https://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>

<h1>Edit Profile</h1>

    <%= form_for @user do |f| %>
    <% flash.each do |key, msg| %>
    <div><%= msg %></div>
    <% end %>

<form>
<div class='col-md-7' 'row-1' >
    <%= f.label :first_name, class:'sr-only'%>
    <%= f.text_field :first_name, placeholder: "First Name", class: 'form-control'%>

    <%= f.label :last_name, class: 'sr-only'%>
    <%= f.text_field :last_name, placeholder: "Last Name", class: 'form-control'%>
</div>

<div class= 'col-md-7' 'row'>
    <%= f.label :user_name, class: 'sr-only' %>
    <%= f.text_field :user_name, placeholder: "User Name", class: 'form-control' %>
</div>

<div class= 'col-md-7' 'row'>
    <%= f.label :city, class: 'sr-only' %>
    <%= f.text_field :city, placeholder: "City", class: 'form-control' %>

    <%= f.label :state, class: 'sr-only' %>
    <%= f.text_field :state, placeholder: "State", class: 'form-control' %>
</div>

<div class= 'col-md-7' 'row'>
    <%= f.label :email, class: 'sr-only' %>
    <%= f.email_field :email, placeholder: "Email", class: 'form-control' %>
</div>

<div class= 'col-md-7' 'row'>
    <%= f.label :password, class: 'sr-only' %>
    <%= f.password_field :password, placeholder: "Password", class: 'form-control' %>

    <%= f.label :password_confirmation, class: 'sr-only' %>
    <%= f.password_field :password_confirmation, placeholder: "Password Confrimation", class: 'form-control' %>
</div>

<div class= 'col-md-7' 'row'>
    <%= f.submit  "Update Profile", class: "btn btn-default" %>
</div>

<% end %>
</div>
</div>
</form>

app/views/users/new.html.erb
<link href='https://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>

<h1>Create New User</h1>


    <%= form_for @user do |f| %>
    <% flash.each do |key, msg| %>
    <div><%= msg %></div>
    <% end %>

<form>
<div class='col-md-7' 'row-1' >
    <%= f.label :first_name, class:'sr-only'%>
    <%= f.text_field :first_name, placeholder: "First Name", class: 'form-control'%>

    <%= f.label :last_name, class: 'sr-only'%>
    <%= f.text_field :last_name, placeholder: "Last Name", class: 'form-control'%>
</div>

<div class= 'col-md-7' 'row'>
    <%= f.label :user_name, class: 'sr-only' %>
    <%= f.text_field :user_name, placeholder: "User Name", class: 'form-control'%>
</div>

<div class= 'col-md-7' 'row'>
    <%= f.label :city, class: 'sr-only' %>
    <%= f.text_field :city, placeholder: "City", class: 'form-control'%>

    <%= f.label :state, class: 'sr-only' %>
    <%= f.text_field :state, placeholder: "State", class: 'form-control'%>
</div>

<div class= 'col-md-7' 'row'>
    <%= f.label :email, class: 'sr-only' %>
    <%= f.email_field :email, placeholder: "Email", class: 'form-control'%>
</div>

<div class= 'col-md-7' 'row'>
    <%= f.label :password, class: 'sr-only'  %>
    <%= f.password_field :password, placeholder: "Password", class: 'form-control'%>

    <%= f.label :password_confirmation, class: 'sr-only' %>
    <%= f.password_field :password_confirmation, placeholder: "Password Confrimation", class: 'form-control'%>
</div>

<div class= 'col-md-7' 'row'>
    <%= f.submit  "Register", class: "btn btn-default btn-sm"%>
</div>

<% end %>
</div>
</div>
</form>

app/views/welcome/index.html.erb
<link href='https://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>

<h1>Now let's get you started...</h1>

  <div class="welcome-page">

<p>Here are some basic guidelines:</p>

  <div class='font-1'>Select ONE Category you would like to browse or create post in.</div>
  <div class='font-1'>Once you select a Category, the most recent post will show.</div>

  <div>To browse all previous post, scroll up.</div>

  <div class='font-1'>When creating a post please make sure you selected the</div>
  <div class='font-1'>correct Category, which your post pertains to.</div>

  <div>Don't forget to share the love and "LIKE" other Users post.</div>
  <div class='font-1'>Feel free to share your post on Facebook!</div>

  <div>Most importantly, PLEASE keep all content postive!</div>

</div>